services:
  postgres:
    image: postgres:15
    container_name: pastai-postgres
    restart: always
    environment:
      POSTGRES_USER: pastai_user
      POSTGRES_PASSWORD: 1471027Demo
      POSTGRES_DB: pastai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:latest
    container_name: pastai-redis
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: pastai-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: pastai-kibana
    ports:
      - "5602:5602"
    environment:
      - ELASTICSEARCH_HOSTS=http://pastai-elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  esdata:
